# Image suffix: browsers
# Image name: playwright
FROM mcr.microsoft.com/playwright:v1.58.2-jammy
ENV PLAYWRIGHT_BROWSERS_PATH=/ms-playwright
ENV XDG_RUNTIME_DIR=/tmp/.chromium
ENV XDG_CACHE_HOME=/tmp/.chromium
ENV NPM_CONFIG_CACHE=/tmp/.npm
RUN apt-get update && apt-get install -y socat \
    && rm -rf /var/lib/apt/lists/* \
    && npx --yes playwright@1.58.2 install firefox \
    && npx --yes playwright@1.58.2 install chromium
# RUN npx --yes playwright@1.58.2 install firefox \
#  && npx --yes playwright@1.58.2 install chromium
# CMD ["bash", "-lc", "CHROMIUM_BIN=$(find /ms-playwright -type f \\( -path '*/chrome-linux/chrome' -o -path '*/chrome-linux64/chrome' \\) | head -n 1) && \"$CHROMIUM_BIN\" --headless --no-sandbox --disable-gpu --remote-debugging-address=0.0.0.0 --remote-debugging-port=9222 about:blank & exec npx playwright@1.58.2 run-server --port 3000"]
CMD ["bash", "-lc", "set -x; CHROMIUM_BIN=$(find /ms-playwright -type f \\( -path '*/chrome-linux/chrome' -o -path '*/chrome-linux64/chrome' \\) | head -n 1); echo \"CHROMIUM_BIN=$CHROMIUM_BIN\"; \"$CHROMIUM_BIN\" --headless --no-sandbox --disable-gpu --remote-debugging-port=9223 about:blank & socat TCP-LISTEN:9222,fork,bind=0.0.0.0 TCP:127.0.0.1:9223 & exec npx playwright@1.58.2 run-server --port 3000"]