services:
  n8n:
    build: .
    image: n8n-playwright-core
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=false
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_EDITOR_BASE_URL=http://localhost:5678
      - N8N_LOG_LEVEL=debug
      - N8N_LOG_OUTPUT=console
      - N8N_COMMUNITY_PACKAGES_ENABLED=true
      - N8N_COMMUNITY_PACKAGES_ALLOW_TOOL_USAGE=true
      - N8N_CUSTOM_EXTENSIONS=/opt/custom-nodes
    develop:
      watch:
        - action: rebuild
          path: ./nodes
    volumes:
      - n8n_data:/home/node/.n8n
      - n8n_cache:/home/node/.cache

  playwright:
    image: ghcr.io/ia-generative/playwright:v1.58.2-jammy-browsers
    build:
      dockerfile: Dockerfile-playwright
    ports:
      - "3000:3000"
      - "9222:9222"

volumes:
  n8n_data:
  n8n_cache: